config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/calendar', to: 'static_pages#calendar'
  get '/projects', to: 'static_pages#projects'
  get '/apply', to: 'static_pages#apply'

  get '/signup', to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/dashboard', to: 'webapp#dashboard'

  get '/myAvailability', to: 'availabilities#showUserAvailability'
  get '/myRequests', to: 'requests#showUserRequests'

  resources :users
  resources :account_activations, :only => [:new, :create, :edit]
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :availabilities, :only => [:index, :new, :create, :update, :destroy]
  resources :requests, :only => [:index, :new, :create, :update, :destroy]
  resources :upcoming_interviews, :only => [:index, :destroy]
  resources :past_interviews, :only => [:index, :show, :edit, :update]
end


=begin
  , :except => [:new] do
    member do
      get :confirm_email
    end
  end

GET     	/users	        index	    users_path          	page to list all users
GET     	/users/1	      show	    user_path(user)	      page to show user
GET	      /users/new	    new	      new_user_path	        page to make a new user (signup)
POST   	  /users	        create	  users_path	          create a new user
GET	      /users/1/edit	  edit	    edit_user_path(user)	page to edit user with id 1
PATCH	    /users/1	      update	  user_path(user)	      update user
DELETE	  /users/1	      destroy	  user_path(user)	      delete user


GET	      /password_resets/new	                          new	          new_password_reset_path
POST	    /password_resets	                              create	      password_resets_path
GET	      http://ex.co/password_resets/<token>/edit	      edit	        edit_password_reset_url(token)
PATCH	    /password_resets/<token>                      	update      	password_reset_path(token)

=end


  # D3 graph data paths
  # get '/leadership_team', to: 'd3_graphs#leadership_team'

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
  
  def new
    render layout: 'application'
  end

  def create
    @user = User.find_by(email: params[:account_activations][:email].downcase)
    if @user
      if @user.activated?
        flash[:info] = "Email already activated"
        redirect_to root_url
      else
        @user.send(:reset_activation_digest)
        @user.send_activation_email
        flash[:info] = "Email sent with account activation instructions"
        redirect_to root_url
      end
    else
      flash.now[:danger] = "Email address not found"
      render 'new'
    end
  end

  def edit
    user = User.find_by(email: params[:email])
    if user && !user.activated? && user.authenticated?(:activation, params[:id])
      if user.expired?(:activation)
        flash[:warning] = "Activation Link Expired!"
        redirect_to new_account_activation_path
      else
        user.activate
        user.update_attribute(:activation_digest, nil)
        flash[:success] = "Account activated! Please log in to continue."
        redirect_to root_url
      end
    else
      flash[:danger] = "Invalid activation link"
      redirect_to root_url
    end
  end

  private

end

app/helpers/account_activation_helper.rb
module AccountActivationHelper
end

app/views/account_activations/new.html.erb
<% provide(:title, "Codeology | Resend Activation Link") %>

<section class="is-fullheight">
  <div class="row">
    <div class="col s12 m6 offset-m3">
      <h2 class="is-size-2 is-size-3-mobile extra-top-padding">Resend Activation Link</h2>

      <%= form_for(:account_activations, url: account_activations_path) do |f| %>
        <div class="input-field">
          <i class="material-icons prefix">mail_outline</i>
            <%= f.email_field :email, class: 'input is-rounded' %>
            <label for="account_activations_email">email</label>          
        </div>
        
        <%= f.submit "Submit", class: "btn white black-text is-round normal-caps", style: "margin-top: 10px;"%> 
        <p class="signup-link">New user? <%= link_to "Sign up now!", signup_path %></p>
      <% end %>

    </div>
  </div>
</section>