config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/calendar', to: 'static_pages#calendar'
  get '/projects', to: 'static_pages#projects'
  get '/apply', to: 'static_pages#apply'

  get '/signup', to: 'users#new'

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '/dashboard', to: 'webapp#dashboard'

  get '/myAvailability', to: 'availabilities#showUserAvailability'
  get '/myRequests', to: 'requests#showUserRequests'

  resources :users
  resources :account_activations, :only => [:new, :create, :edit]
  resources :password_resets, :only => [:new, :create, :edit, :update]
  resources :availabilities, :only => [:index, :new, :create, :update, :destroy]
  resources :requests, :only => [:index, :new, :create, :update, :destroy]
  resources :upcoming_interviews, :only => [:index, :destroy]
  resources :past_interviews, :only => [:index, :show, :edit, :update]
end


=begin
  , :except => [:new] do
    member do
      get :confirm_email
    end
  end

GET     	/users	        index	    users_path          	page to list all users
GET     	/users/1	      show	    user_path(user)	      page to show user
GET	      /users/new	    new	      new_user_path	        page to make a new user (signup)
POST   	  /users	        create	  users_path	          create a new user
GET	      /users/1/edit	  edit	    edit_user_path(user)	page to edit user with id 1
PATCH	    /users/1	      update	  user_path(user)	      update user
DELETE	  /users/1	      destroy	  user_path(user)	      delete user


GET	      /password_resets/new	                          new	          new_password_reset_path
POST	    /password_resets	                              create	      password_resets_path
GET	      http://ex.co/password_resets/<token>/edit	      edit	        edit_password_reset_url(token)
PATCH	    /password_resets/<token>                      	update      	password_reset_path(token)

=end


  # D3 graph data paths
  # get '/leadership_team', to: 'd3_graphs#leadership_team'

app/views/layouts/_error_messages.html.erb
<% if @user.errors.any? %>
  <div class="notification is-danger">
    <ul class="collection">
    <li class="collection-items">The form contains <%= pluralize(@user.errors.count, "error") %>.</li>
    <% @user.errors.full_messages.each do |msg| %>
      <li class="collection-items"><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_navbar.html.erb
<!-- NAVIGATION BAR -->
    <div class="navbar-fixed">
      <nav class="white">
        <div class="nav-wrapper">
          <%= link_to image_tag("codeology_logo_padded.png", class: "nav-image"), root_path, :class => "brand-logo"%>
          <a data-target="mobile-nav" class="sidenav-trigger"><i class="grey-text text-darken-3 fa fa-3x fa-bars"></i></a>

          <ul class="right hide-on-med-and-down">
            <li>
            <a class="" href="https://www.instagram.com/berkeleycodeology/" target="_blank">
              <span class="" style="color: #222;"><i class="fa fa-instagram"></i></span></a>
            </li>
            <li>
            <a class="" href="https://github.com/CodeologyClub" target="_blank">
              <span class="" style="color: #333;"><i class="fa fa-github"></i></span></a>
            </li>
            <li>
            <a class="" href="https://www.linkedin.com/company/berkeley-codeology/" target="_blank">
              <span class="" style="color: #007bb6;"><i class="fa fa-linkedin-square"></i></span></a>
            </li>
            <li>
            <a class="" href="https://www.facebook.com/berkeleycodeology/" target="_blank">
              <span class="" style="color: #3B5998;"><i class="fa fa-facebook-f"></i></span></a>
            </li>

            <li><%= link_to root_path, :class => "grey-text text-darken-3" do %>Home <% end %></li>
            <li><%= link_to about_path, :class => "grey-text text-darken-3" do %> About <% end %></li>
            <li><%= link_to projects_path, :class => "grey-text text-darken-3" do %> Projects <% end %></li>
            <li><%= link_to calendar_path, :class => "grey-text text-darken-3" do %> Calendar <% end %></li>
            <li><%= link_to apply_path, :class => "grey-text text-darken-3" do %> Apply <% end %></li>
            <!--
            -->
            <% if user_is_logged_in? %>
            <li><%= link_to dashboard_path, :class => "grey-text text-darken-3" do %> Dashboard <% end %></li>
              <li><%= link_to logout_path, method: :delete, :class => "grey-text text-darken-3" do %> Logout <% end %> </li>
            <% else %>
            <li><%= link_to login_path, :class => "grey-text text-darken-3" do %> Login <% end %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </div>

    <ul class="sidenav" id="mobile-nav">
      <li><%= link_to root_path, :class => "grey-text text-darken-3" do %> Home <% end %></li>
      <li><%= link_to about_path, :class => "grey-text text-darken-3" do %> About <% end %></li>
      <li><%= link_to projects_path, :class => "grey-text text-darken-3" do %> Projects <% end %></li>
      <li><%= link_to calendar_path, :class => "grey-text text-darken-3" do %> Calendar <% end %></li>
      <li><%= link_to apply_path, :class => "grey-text text-darken-3" do %> Apply <% end %></li>
      <!--
      -->
      <% if user_is_logged_in? %>
      <li><%= link_to dashboard_path, :class => "grey-text text-darken-3" do %> Dashboard <% end %></li>
        <li><%= link_to logout_path, method: :delete, :class => "grey-text text-darken-3" do %> Logout <% end %> </li>
      <% else %>
      <li><%= link_to login_path, :class => "grey-text text-darken-3" do %> Login <% end %></li>
      <% end %>

      <li>
      <a class="" href="https://www.instagram.com/berkeleycodeology/" target="_blank">
        <span class="" style="color: #222;"><i class="fa fa-instagram"></i></span></a>
      </li>
      <li>
      <a class="navbar-item" href="https://github.com/CodeologyClub" target="_blank">
        <span class="icon" style="color: #333;"><i class="fa fa-lg fa-github"></i></span></a>
      </li>
      <li>
      <a class="navbar-item" href="https://www.linkedin.com/company/berkeley-codeology/" target="_blank">
        <span class="icon" style="color: #007bb6;"><i class="fa fa-lg fa-linkedin-square"></i></span></a>
      </li>
      <li>
      <a class="navbar-item" href="https://www.facebook.com/berkeleycodeology/" target="_blank">
        <span class="icon" style="color: #3B5998;"><i class="fa fa-lg fa-facebook-f"></i></span></a>
      </li>
    </ul>

  <script type="text/javascript">
    $('.sidenav').sidenav();
  </script>
</nav>

app/views/layouts/_project_cards.html.erb
<div class="row">
  <% @projects.each do |element| %>
    <div class="col s12 m4">
      <div class="card small hoverable">
        <div class="card-image waves-effect waves-block waves-light">
          <%= image_tag(element[:imgurl], :alt=>"project image", :class=>"image activator", :style=>"object-fit: cover;") %>
        </div>
        <div class="card-content">
          <p class="is-size-4 truncate activator"><%= element[:name] %></p>
          <p class="activator"><i class="material-icons right">arrow_drop_up</i></p>
        </div>
        <div class="card-reveal">
          <span class="card-title is-size-4 is-size-6-mobile grey-text text-darken-4"><%= element[:name] %><i class="material-icons right">arrow_drop_down</i></span>
          <p><%= element[:blurb] %></p>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/_sideNav.html.erb
<!-- NAVIGATION BAR -->
<div class="navbar-fixed">
  <nav class="white">
    <div class="nav-wrapper">
      <a data-target="mobile-nav" class="sidenav-trigger"><i class="grey-text text-darken-3 fa fa-3x fa-bars"></i></a>
    </div>
  </nav>
</div>

<ul class="sidenav sidenav-fixed" id="mobile-nav">
  <li><div class="user-view">
    <div class="background">
      <%= image_tag("office.jpg", alt: "logo")  %>
    </div>
    <%= link_to root_url do %>
      <%= image_tag("codeology_logo_padded.png", alt: "logo", class: "is-round hoverable", style: "width: 225px !important")  %>
    <% end %>
    <%= link_to user_path(@curr_user) do %>
      <span class="grey-text text-darken-4 name" style="font-weight:bold;"><%= @curr_user.name %></span>
    <% end %>
    <%= link_to user_path(@curr_user) do %>
      <span class="grey-text text-darken-4 email" style="font-weight:bold;"><%= @curr_user.email %></span>
    <% end %>
  </div></li>
  <li><%= link_to dashboard_path, :class => "grey-text text-darken-4 waves-effect waves-green" do %><i class="material-icons">tv</i> Dashboard <% end %></li>
  <li><%= link_to availabilities_path, :class => "grey-text text-darken-4 waves-effect waves-green" do %><i class="material-icons">work_outline</i> Others Availabilities <% end %></li>
  <li><%= link_to myAvailability_path, :class => "grey-text text-darken-4 waves-effect waves-green" do %><i class="material-icons">chat_bubble_outline</i> My Availabilities <% end %></li>
  <li><%= link_to requests_path, :class => "grey-text text-darken-4 waves-effect waves-green" do %><i class="material-icons">work_outline</i> Others Requests <% end %></li>
  <li><%= link_to myRequests_path, :class => "grey-text text-darken-4 waves-effect waves-green" do %><i class="material-icons">chat_bubble_outline</i> My Requests <% end %></li>
  <li><%= link_to upcoming_interviews_path, :class => "grey-text text-darken-4 waves-effect waves-green" do %><i class="material-icons">date_range</i> Upcoming <% end %></li>
  <li><%= link_to past_interviews_path, :class => "grey-text text-darken-4 waves-effect waves-green" do %><i class="material-icons">insert_chart_outlined</i> Completed <% end %></li>
  <li><%= link_to users_path, :class => "grey-text text-darken-4 waves-effect waves-green" do %><i class="material-icons">people_outline</i> Member Directory <% end %></li>
  <li>
    <ul class="collapsible">
      <li>
        <a class="collapsible-header grey-text text-darken-4 waves-effect waves-green"><i class="material-icons">settings_applications</i> Options</a>
        <div class="collapsible-body">
          <ul>
            <li><%= link_to root_url, :class => "grey-text text-darken-4 waves-effect waves-green" do %><i class="material-icons">open_in_browser</i> Back to Website <% end %></li>
            <li><%= link_to user_path(@curr_user), :class => "grey-text text-darken-4 waves-effect waves-green" do %><i class="material-icons">settings</i> Settings <% end %></li>
            <li><a rel="nofollow" data-method="delete" href="/logout" class="grey-text text-darken-4 waves-effect waves-green"><i class="icon-flipped material-icons">exit_to_app</i>Log Out</a></li> 
          </ul>
        </div>
      </li>
    </ul>
  </li>
</ul>

<script type="text/javascript"> 
  $('.sidenav').sidenav();
  $('.collapsible').collapsible();
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="google-site-verification" content="QFnKlIoSssBp0lO6N1Vv7k-naWkoNtFhWtt9HrQD4uA" />
    <title><%= yield :title || "Codeology" %></title>
    <!--<link href="./../../assets/mini_logo.png" rel="icon">-->
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>

    <!-- STYLESHEETS -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karla|Roboto">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- VIEWPORT -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>
  <body>
    <!-- NAVBAR -->
    <div>
    <%= render "layouts/navbar" %>
    </div>

    <!-- MAIN CONTENT -->
    <div id="main-content-container" class="">
      <!-- NOTIFICATIONS -->
      <% if flash.any? %>
      <div class="container is-round collection has-text-centered">
        <% flash.each do |key, value| %>
          <p class="collection-item is-<%= key %>"><%= value %></p>
        <% end %>
      <% end %>
      </div>

      <%= yield %>
    </div>
  </body>

  <footer class="page-footer grey lighten-2">
    <div class="container">

    </div>
    <div class="footer-copyright grey lighten-2">
      <div class="container">
        <div class="row has-text-centered">
          <!--<div class="col s4">
            <a class="" href="https://www.instagram.com/berkeleycodeology/" target="_blank">
              <span class="icon" style="color: #222;">
                <i class="fa fa-lg fa-instagram"></i>
              </span>
            </a>
          </div>-->
          <div class="col s4">
            <a class="" href="https://github.com/CodeologyClub" target="_blank">
              <span class="icon" style="color: #333;">
                <i class="fa fa-lg fa-github"></i>
              </span>
            </a>
          </div>
          <div class="col s4">
            <a class="" href="https://www.linkedin.com/company/berkeley-codeology/" target="_blank">
              <span class="icon" style="color: #007bb6;">
                <i class="fa fa-lg fa-linkedin-square"></i>
              </span>
            </a>
          </div>
          <div class="col s4">
            <a class="" href="https://www.facebook.com/berkeleycodeology/" target="_blank">
              <span class="icon" style="color: #3B5998;">
                <i class="fa fa-lg fa-facebook-f"></i>
              </span>
            </a>
          </div>
        </div>
      </div>
    </div>
  </footer>
</html>

app/views/layouts/web_application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="google-site-verification" content="QFnKlIoSssBp0lO6N1Vv7k-naWkoNtFhWtt9HrQD4uA" />
    <title><%= yield :title || "Codeology" %></title>
    <!--<link href="./../../assets/mini_logo.png" rel="icon">-->
    <%= favicon_link_tag 'favicon.ico' %>
    <%= csrf_meta_tags %>
    
    <!-- STYLESHEETS -->
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Karla|Roboto">
	  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <!-- VIEWPORT -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  </head>

  <body>
    <!-- NAVPANEL -->
    <%= render "layouts/sideNav" %>


    <!-- MAIN CONTENT -->
    <div class="adjustable-container">
      <!-- NOTIFICATIONS -->
      <% if flash.any? %>
      <div class="container is-round collection has-text-centered">
        <% flash.each do |key, value| %>
          <p class="collection-item is-<%= key %>"><%= value %></p>
        <% end %>
      </div>
      <% end %>
      <!-- YIELD PAGE -->
      <%= yield %>
    </div>
  </body>
</html>